import java.util.ArrayList;
import java.util.Collections;

public class homeworkProblem12 {

    public static ArrayList<String> kmerComposition(String dna, int kmerSize){
        ArrayList<String> kmerList = new ArrayList<>();

        for (int i = 0; i < dna.length() - kmerSize + 1; i++){
            String kmer = dna.substring(i, i + kmerSize);
            kmerList.add(kmer);
        }

        Collections.sort(kmerList);

        return kmerList;
    }

    public static void main(String[] args){
        ArrayList<String> kmerList = new ArrayList<>();
        String dna = "GCAGGGCACCTACATCGCTCTCCTGTATGCCTCTTAGGCGATGTGGAAAACTAGGAACTGTGATACATATAGCACGGGAAGGGGACTTAGTATGGCGACGCGACGTAGACGCCGTTACCTTACGCCACCTGCGCGGAGGCCCCCTGCCCCGGTATTATAGCCCCAGGCCGCAGCCCGATCGTTGGAGAGGTTCAAAGGACTAGCGGGGCACTTACAAAAGCTATTTGATTGCATCTGACACACCTTAATGAAATAGCCTAGGCGGGAGTCCCACAGGGGTATTATCTTCATTTAACGTTATGGGAGAAGCTAAGCGTTTCAGTGCAGAATCTCGCCTTTAGACTTCCTCATAGTTGGCCGCAAGAACGTGTATTGACGAGAAACCAAATATGCATAATATCAGGACTCTAGCGATGTTGAATGCAGCTCAAGTAAGGTGAAATTCACCCTGTTGCGCTATGCGCCGATTTTAGGGATGAGGAGTAGGGCTTTTAAAGATCAGCCGGACCGATACTAGTCTCTTCATTTGACCATGGGGGCAACGAAATGCTAGGTAACGTAGGTTAAGCTCAAAGTTGAACCACAGAGGTGCGAGTTTAAGTAACATAAGCCTGCATAACCAAGTAAAAGTATCATCGTCAAGACTGCGCTATAATCATCGGTAAAGAACACCCCGTATTGGCTCTGAGGCGGGCTGCGATACCCGACGAGGAACTAATACACGTACCCGCTAGTTCAGCGTCACGTGTACGAATCGGAGTTGTCCAGCCGCAAAAGGGTGTGCTTCCTGCCATCGTCGCCTGCGCAGAATTACACCTATGTTCCATTCGGCACTCCAAGGCACAGGCACTAATGAACTGTGCTGGTATGTTATGAAAACGTAAAATCGAATATGACACGGATGAAGACGTGTATCGCGCCAGTTCACCGCATCGTCCCCAACTCACCACTTAGACCTAATACACGTGGGCAACAAAAAGGAGGCCCGCACGCAGCCTTT";
        int kmerSize = 50;

        kmerList = (kmerComposition(dna, kmerSize));

        for (int i = 0; i < kmerList.size(); i++){
            System.out.println(kmerList.get(i));
        }
    }
}
